### PR TITLE
[WIP]#157513754 creazione servizio restful /notifications/register

### PR DESCRIPTION
**Pull request by Deeemi**
Creation of the REST /subscriptions service exposed to Italy-PagoPA-Proxy to receive data relating to a citizen who wants to subscribe to the PagoPA alerting service, transformation of the received data and creation of SOAP Client to Nodo Avvisatura (nodoAggiornaIscrizioneAvvisatura).

### CODE REVIEW

**Comment by cloudify** [comment]
Thanks! A couple of notes:

1. write in English
1. in this PR, for one single functionality, ~150 files, 17K+6K ~= 24K lines of code needs to be reviewed (that's the same amount of lines of code of ALL our repos COMBINED) 
1. don't put actions in REST resources, the resource you want to expose is probably something like `/notification_subscriptions` that could be shortened to `/subscriptions`

**Comment by cloudify** [comment]
Finally, this repository is meant to provide the API (WSDL and interfaces) to interact with pagopa.

The REST endpoint should be part of `italia-pagopa-proxy`!!!

**Comment by cloudify** [comment]
Other things that are wrong with this PR:

* the `dist` folder has been removed (that's the only way we have to make the code importable by `italia-pagopa-proxy`
* the permission of all files have been changed to `0755`
* `yarn-error.log` has been committed

**Comment by Deeemi** [comment]
This code will be moved under italia-pagopa-proxy

**Pull request closed without merging**
